const express=require("express");
const cors=require("cors");
const orderRoutes=require("./routes/order.routes");
const webhookRoutes=require("./routes/webhook.routes");
const reconciliationRoutes=require("./routes/reconciliation.routes");
const incidentRoutes=require("./routes/incident.routes");
const razorpayConnectionRoutes=require("./routes/razorpay.connection.routes");
const authRoutes=require("./routes/auth.routes");
const dashboardRoutes=require("./routes/dashboard.routes");
const proofRoutes=require("./routes/proof.routes");
const policyRoutes=require("./routes/policy.routes");
const paymentLinkRoutes=require("./routes/payment-link.routes");
const app=express();
app.use(cors({origin:process.env.FRONTEND_ORIGIN||true,credentials:true}));
app.use("/api/webhooks",webhookRoutes);
app.use(express.json());
app.use("/api/auth",authRoutes);
app.use("/api/razorpay",razorpayConnectionRoutes);
app.use("/api/dashboard",dashboardRoutes);
app.use("/api/proof",proofRoutes);
app.use("/api/policy",policyRoutes);
app.use("/api/payment-links",paymentLinkRoutes);
app.get("/health",(req,res)=>res.json({success:true,service:"RecoverAI Backend",status:"healthy",time:new Date().toISOString()}));
app.use("/api/orders",orderRoutes);
app.use("/api/reconciliation",reconciliationRoutes);
app.use("/api/incidents",incidentRoutes);
module.exports=app;
